---
title: "Female_Death"
author: "Hannah & Bennet"
date: "5/11/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Female Deaths 2017 ALL AGES
#read in data, created tibble

female_deaths <- read_html("https://www.cdc.gov/women/lcod/2017/all-races-origins/index.htm#anchor_1571151327")
female_deaths <-html_nodes(female_deaths, css = "table")
female_deaths<-html_table(female_deaths)[[1]]
female_deaths_tibble<-as_tibble(female_deaths)

    Top10_Female_Deaths<-female_deaths_tibble%>%
      mutate(
        Percent= parse_number(Percent)
      )%>%
      rename(
        Female_Death_causes =`All races and origins, Female, All ages`
      )
write_csv(Top10_Female_Deaths,"~/Mscs 264b S21/Project/Hannah and Bennet/Top10_Female_Deaths_table.csv")
```

```{r}
#Female Deaths 2017 BY AGE GROUP
#read in data, created tibble

female_death_age <- read_html("https://www.cdc.gov/women/lcod/2017/all-races-origins/index.htm#anchor_1571151327")
female_deaths_age <-html_nodes(female_death_age, css = "table")
female_death_age<-html_table(female_deaths_age)[[2]]
female_death_age[1,]
colnames(female_death_age) <-female_death_age[1,]
female_death_tibble<-as_tibble(female_death_age[-1,])
```

```{r}
#pivoting the data into different columns 
tidy2<-female_death_tibble%>%
  pivot_longer(c( `1-19 years`, `20-44 years`,`45-64 years`,`65-84 years`,`85+ years`,`All ages`), names_to = "age", values_to = "type")%>%
  separate(type, into = c("cause", "percent"), sep = "\n")%>%
   mutate(
                    percent= parse_number(percent)
                  )
write_csv(tidy2,"~/Mscs 264b S21/Project/Hannah and Bennet/Female_deaths_age.csv")
```

```{r}
#testing graph
#code used in shiny
filter(age == input$barcharty) %>%
    ggplot(aes(x=fct_reorder(cause,percent),percent), y = percent) +
    geom_col() +
    coord_flip() +
    labs(
      x = "Cause of Death",
       y = "Percent %"
    )+
    theme(legend.position = "none")
```

## Female Deaths By Race

```{r}
#read in data, created tibble

female_death_race <- read_html("https://www.cdc.gov/women/lcod/2017/byraceandhispanic/index.htm")
female_deaths_race <- html_nodes(female_death_race, css = "table")
female_death_race <- html_table(female_deaths_race)[[1]]
female_death_race[1,]
colnames(female_death_race) <- female_death_race[1,]
female_death_race_tibble <- as_tibble(female_death_race[-1,])


#pivot and tidy
tidy_race_f <- female_death_race_tibble %>%
  pivot_longer(c( `Non-Hispanic white`, `Non-Hispanic black`,`Non-Hispanic American Indian or Alaska Native`,`Non-Hispanic Asian or Pacific Islander`,`Hispanic`,`All races and origins`), names_to = "race", values_to = "type") %>%
  separate(type, into = c("cause", "percent"), sep = "\n") %>%
  mutate(percent= parse_number(percent))

write_csv(tidy_race_f,"~/Mscs 264b S21/Project/Hannah and Bennet/female_deaths_race.csv")

```

```{r}
#plot test

  race_test_f <-tidy_race_f %>%
  filter(race == "Non-Hispanic white") %>%
  mutate(cause = fct_reorder(cause,percent,.desc = TRUE), percent) %>%
  ggplot(aes(x=cause))+
          geom_col(aes(y=percent)) #+
          #coord_flip()+
    labs(
      x = "Top 10 Causes of Death",
      y = "Percent %"
    )+
   theme(
     legend.title = element_blank(),
     legend.position = "none")
   ggplotly(race_test_f)
   
   
   
  
```



